name: aplikasi_travel_wisata_lokal
description: 'Aplikasi Wisata Lokal dengan Peta dan Database SQLite.'
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # --- Database ---
  sqflite: ^2.3.0
  path: ^1.8.3

  # --- Peta (OpenStreetMap) ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0 # Untuk GPS Lokasi Saat Ini

  # --- Fitur Lain ---
  image_picker: ^1.0.4 # Ambil Foto
  intl: ^0.19.0 # Format Tanggal
  http: ^1.2.0 # Untuk API Alamat (Nominatim)
  url_launcher: ^6.2.5 # Untuk Buka Google Maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Library Icon & Splash (Biarkan di sini untuk tools)
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Daftarkan folder assets
  assets:
    - assets/images/

# 1. Konfigurasi Icon Aplikasi (TETAP ADA)
flutter_launcher_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/images/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#0xFF016B61'
  adaptive_icon_foreground: 'assets/images/icon.png'
